<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #000; padding-bottom: 10px; }
        .report-info { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #f2f2f2; text-align: left; padding: 8px; border: 1px solid #ccc; }
        td { padding: 8px; border: 1px solid #ccc; }
        .status-good { color: #10b981; font-weight: bold; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #777; }
    </style>
</head>
<body>
    <div class="header">
        <h1>AutoNexus Performance Report</h1>
        <p>Mechanic Activity & Efficiency</p>
    </div>

    <div class="report-info">
        <strong>Date:</strong> <?= htmlspecialchars($date ?? 'All Time') ?><br>
        <strong>Generated On:</strong> <?= date('Y-m-d H:i') ?>
    </div>

    <table>
        <thead>
            <tr>
                <th>Mechanic</th>
                <th>Code</th>
                <th>Assigned</th>
                <th>Completed</th>
                <th>In Progress</th>
                <th>Avg Mins</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($activity as $row): ?>
            <tr>
                <td><?= $row['mechanic_name'] ?></td>
                <td><?= $row['mechanic_code'] ?></td>
                <td><?= $row['total_assigned'] ?></td>
                <td class="status-good"><?= $row['completed'] ?></td>
                <td><?= $row['in_progress'] ?></td>
                <td><?= round($row['avg_duration_mins'] ?? 0, 0) ?> min</td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div style="text-align: center; margin-top: 20px;">
    <h3>Completion Comparison</h3>
    <?php if (isset($_POST['chart1_data'])): ?>
        <img src="<?= $_POST['chart1_data'] ?>" style="width: 100%; max-width: 500px;">
    <?php else: ?>
        <p>Chart data not available</p>
    <?php endif; ?>
</div>

<div style="text-align: center; margin-top: 20px;">
    <h3>Technician Speed</h3>
    <?php if (isset($_POST['chart2_data'])): ?>
        <img src="<?= $_POST['chart2_data'] ?>" style="width: 100%; max-width: 500px;">
    <?php else: ?>
        <p>Chart data not available</p>
    <?php endif; ?>
</div>

    <div class="footer">
        Generated by AutoNexus Information System - UCSC Group Project
    </div>


</body>
</html>